group: edge
sudo: required

language: go
go: 
  - 1.7.1

services: 
  - docker

install:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - make build

after_success:
  - make docker-build
  - make docker-push
