group: edge
sudo: required

language: go
go: 
  - 1.7.1

services: 
  - docker

install:
  - go get -u github.com/golang/lint/golint

script: 
  - make build

before_deploy:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

deploy:
  - make docker-build
  - make docker-push
