goddd:
    image: marcusolsson/goddd
    ports:
        - 8080:8080
    environment:
        ROUTINGSERVICE_URL: http://pathfinder:8080
    links:
        - pathfinder

pathfinder:
    image: marcusolsson/pathfinder
    ports:
        - 8080

appdash:
    image: rebder/appdash
    ports:
        - 8699:8699 
        - 8700:8700
